version: '3'

services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    networks:
      - dbnet
    environment:
      - POSTGRES_PASSWORD=s3cret
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
      - 3306:3306
  activemq:
    container_name: activemq
    image: webcenter/activemq
    environment:
      ACTIVEMQ_CONFIG_MINMEMORY: 128
      ACTIVEMQ_CONFIG_MAXMEMORY: 256
    ports:
      - 8161:8161
      - 62616:61616

  app:
    container_name: app
    depends_on:
      - activemq
    image: flightsinfo:v1.1
    volumes:
      - ./:/app
    networks:
      - dbnet
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ACTIVE_MQ_BROKER_URL: tcp://activemq:62616
    ports:
      - 9090:9090
networks:
  dbnet:
