version: '3'

services:
  app:
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: ./build/libs/flights-0.0.1-SNAPSHOT.jar
    ports:
      - 8080:8080
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
