insert into FLIGHT (ID, NUMBER, FLIGHT_DATE, FROM_AIRPORT, TO_AIRPORT) values (FLIGHT_ID_SEQ.NEXTVAL, 'A101','20-OCT-2019','DAL', 'HOU');
insert into FLIGHT (ID, NUMBER, FLIGHT_DATE, FROM_AIRPORT, TO_AIRPORT) values (FLIGHT_ID_SEQ.NEXTVAL, 'A102','20-OCT-2019','HOU', 'DAL');
insert into FLIGHT (ID, NUMBER, FLIGHT_DATE, FROM_AIRPORT, TO_AIRPORT) values (FLIGHT_ID_SEQ.NEXTVAL, 'A103','20-OCT-2019','DAL', 'SAN');
insert into FLIGHT (ID, NUMBER, FLIGHT_DATE, FROM_AIRPORT, TO_AIRPORT) values (FLIGHT_ID_SEQ.NEXTVAL, 'A104','20-OCT-2019','SAN', 'HOU');
commit;